language: go
go_import_path: github.com/CodyGuo/glog
git:
  depth: 1
env:
  - GO111MODULE=on
go: [1.13.x, 1.14.x]
os: [windows, linux, osx]
script:
  - go build ./examples/main.go
  - export GOMAXPROCS=4
  - export GORACE=halt_on_error=1
  - go test -v ./...
  - go test -race -v ./...
  - go test -bemch -v ./... -benchmem
