language: go
go_import_path: github.com/CodyGuo/glog
git:
  depth: 1
env:
  - GO111MODULE=on
go: [1.12.x, 1.13.x, 1.14.x]
os: [windows, linux, osx]
script:
  - export GOMAXPROCS=4
  - export GORACE=halt_on_error=1
  - cd examples && go build
  - go run ./examples/...
  - go test -v .
  - go test -race -v ./...
  - go test -bench . -v -benchmem
